name: NPM Custom Action
description: Install and Cache NPM Packages
inputs:
  docker-username:
    required: true
    description: DockerHub username
  docker-password:
    required: true
    description: DockerHub password
  github-owner:
    required: true
    description: Github username
  github-token:
    required: true
    description: Github Token
runs:
  using: "composite"
  steps:
    - name: Dockerhub Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2.2.0
      with:
        registry: ghcr.io
        username: ${{ inputs.github-owner }}
        password: ${{ inputs.github-token }}