name: NPM Custom Action
description: Install and Cache NPM Packages
runs:
  using: "composite"
  steps:
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}     

    - name: Install Dependencies
      run: npm install
      shell: bash