name: Testing Self-Hosted Runner
on:
  workflow_dispatch:  

jobs:
  assign-label:
    runs-on: [self-hosted, linux, prod, 1234]
    steps:
      - name: Echo Content
        run: |
          echo Ok
          slepp 600
